### PR TITLE
Update to Swift 4.1

### PR DESCRIPTION
**Pull request by OmarPedraza**
Update code and project to Swift 4.1 requirements

### CODE REVIEW

**Comment by OmarPedraza** [comment]
Closed till issues where resolved

**Comment by lxcid** [comment]
Hey @OmarPedraza! Both PRs looks promising! Should we reconsider?

**Comment by OmarPedraza** [comment]
Hi @lxcid,
I closed both because they didn't passed the tests. I'm working on it and I'll update them as soon as possible.

Thanks for considering them!

**Comment by lxcid** [comment]
@OmarPedraza Thanks so much man! Much appreciated!

I think the problem is that Travis CI still using Xcode 8

I'll update to the latest xcode9.3beta

https://docs.travis-ci.com/user/reference/osx/#OS-X-Version

**Pull request closed without merging**
